"""Публичные классы данных колбэков, переэкспортируемые для всего слоя бота."""

from app.bot.callbacks.admin import (
    AdminActionLogCallback,
    AdminDashboardCallback,
    AdminDeletedHabitActionCallback,
    AdminFeedbackCallback,
    AdminFeedbackActionCallback,
    AdminPageCallback,
    AdminUserActionCallback,
    AdminUserCallback,
)
from app.bot.callbacks.create_habit import CreateHabitCallback
from app.bot.callbacks.feedback import FeedbackCallback
from app.bot.callbacks.habit import (
    HabitArchiveCallback,
    HabitDeleteCallback,
    HabitDeleteConfirmCallback,
    HabitDoneCallback,
    HabitEditCallback,
    HabitEditActionCallback,
    HabitEditCancelCallback,
    HabitGoalActionCallback,
    HabitGoalMenuCallback,
    HabitHistoryCallback,
    HabitListCallback,
    HabitListSource,
    HabitPauseCallback,
    HabitReturnTarget,
    HabitReminderCancelCallback,
    HabitReminderDisableCallback,
    HabitReminderMenuCallback,
    HabitReminderSetTimeCallback,
    HabitResumeCallback,
    HabitRestoreCallback,
    HabitStatsCallback,
    HabitViewCallback,
)
from app.bot.callbacks.navigation import OpenProgressCallback, OpenTodayCallback

__all__ = [
    "AdminDashboardCallback",
    "AdminPageCallback",
    "AdminUserCallback",
    "AdminUserActionCallback",
    "AdminFeedbackCallback",
    "AdminFeedbackActionCallback",
    "AdminActionLogCallback",
    "AdminDeletedHabitActionCallback",
    "CreateHabitCallback",
    "FeedbackCallback",
    "HabitListSource",
    "HabitReturnTarget",
    "HabitViewCallback",
    "HabitDoneCallback",
    "HabitEditCallback",
    "HabitEditActionCallback",
    "HabitEditCancelCallback",
    "HabitGoalMenuCallback",
    "HabitGoalActionCallback",
    "HabitHistoryCallback",
    "HabitReminderMenuCallback",
    "HabitReminderSetTimeCallback",
    "HabitReminderDisableCallback",
    "HabitReminderCancelCallback",
    "HabitStatsCallback",
    "HabitArchiveCallback",
    "HabitPauseCallback",
    "HabitResumeCallback",
    "HabitRestoreCallback",
    "HabitDeleteCallback",
    "HabitDeleteConfirmCallback",
    "HabitListCallback",
    "OpenTodayCallback",
    "OpenProgressCallback",
]
